### ISSUE TITLE
Use Right shift as dead key ?

### ISSUE THREAD

**Issue by clementnuss** [pieter-degroote/UltimateKEYS#1]
Thank you for this AHK script, it works really well (way better than Windows Intl Keyboard) 👏👏

I have one request though, is it possible to also use the right shift as a deadkey modifier (in addition to AltGr) ?

I am never using this key and it is easier to type than AltGr.

**Comment by pieter-degroote** [comment]
You can modify a line like :

`>!5::Send {u+20ac}   ; (€) euro sign on Right Alt modifier`

to :
`>+5::Send {u+20ac}   ; (€) euro sign on Right Shift modifier`


Or you can modify the top line in this example :

```
>!6::  ; Right Alt modifier
  Input, key, L1, {bs}{del}{esc}{home}{end}
  Send % dkCircumflex.item[key]
return
```

to :
```
>+6::  ; Right Shift modifier
  Input, key, L1, {bs}{del}{esc}{home}{end}
  Send % dkCircumflex.item[key]
return
```

Please note that in both examples, the symbol "**>!**" changes to "**>+**".

See also the documentation at :  [https://www.autohotkey.com/docs/Hotkeys.htm](https://www.autohotkey.com/docs/Hotkeys.htm)

**Comment by clementnuss** [comment]
Thank you, this would indeed solve this issue.
One last question: I have looked at the AHK documentation, but have not found a solution to be able to use either the right shift `>+` or AltGr `>!`, with a OR modifier, e.g.:
 `>!5: OR >+5:Send {u+20ac} ; (€) euro sign on Right Alt modifier!`
Do you know if this is possible ?

**Comment by pieter-degroote** [comment]
Simply put these 2 lines together as :

```
>!5::Send {u+20ac}   ; (€) euro sign (Right Alt modifier)
>+5::Send {u+20ac}   ; (€) euro sign (Right Shift modifier)
```

and those 2 sections as :

```
>!6::  ; Right Alt modifier
  Input, key, L1, {bs}{del}{esc}{home}{end}
  Send % dkCircumflex.item[key]
return
>+6::  ; Right Shift modifier
  Input, key, L1, {bs}{del}{esc}{home}{end}
  Send % dkCircumflex.item[key]
return
```

**Comment by clementnuss** [comment]
That's what I thought.
Thank you for your time and for this great project 👍

**Comment by pieter-degroote** [comment]
**Please also take a look at this post :**

**[Important - Only use "BASIC LATIN" (codes 32 to 126) for Windows/Microsoft or Linux passwords !](https://github.com/pieter-degroote/UltimateKEYS/issues/3)**
