### ISSUE TITLE
The German alphabet has a new official letter the capital ẞ (U+1E9E)

### ISSUE THREAD

**Issue by getreu** [pieter-degroote/UltimateKEYS#10]
The German alphabet has a new official letter the capital ẞ (U+1E9E) for some years now.

In EurKey 1.3 beta it is mapped to AltGr-Shift-s. I suggest doing so here also.

**Comment by pieter-degroote** [comment]
This change (capital Eszett, ẞ) has now been published in the latest releases :

[UltimateKEYS - Releases](https://github.com/pieter-degroote/UltimateKEYS/releases)
[UltimateKEYS - Testing Releases](https://github.com/pieter-degroote/UltimateKEYS-testing/releases)
