### ISSUE TITLE
Suggestion: second AltGr key (CapsLock)

### ISSUE THREAD

**Issue by getreu** [pieter-degroote/UltimateKEYS#11]
To improve ergonomics, a second [AltGr] key is very handy. I tried some alternatives and found the best solution is to map the [CapsLock] key to the [AltGr] function. I mapped the original [CapsLock] function to [Shift left]-[Shift right]. The mapping for Linux and Windows is described in this [blogs](https://blog.getreu.net/tags/eurkey/). My suggestion is to include this mapping in UltimateKeys.

Off topic: btw: I like your choice for  õ and ã a lot!

**Comment by pieter-degroote** [comment]
These changes ('Caps Lock' mod to 'Right Alt' and capital Eszett (ẞ)) have now been published in the latest releases :

[UltimateKEYS - Releases](https://github.com/pieter-degroote/UltimateKEYS/releases)
[UltimateKEYS - Testing Releases](https://github.com/pieter-degroote/UltimateKEYS-testing/releases)

Regards.
