### ISSUE TITLE
in real time

### ISSUE THREAD

**Issue by janjonckers** [pieter-degroote/UltimateKEYS#2]
![20200613_005052](https://user-images.githubusercontent.com/66851819/84553923-e8361b80-ad15-11ea-9a55-ae0f37d18fed.jpg)

I was thinking that I should make it more tactile for myself ...

**Comment by pieter-degroote** [comment]
Beautiful, looks great !
This is the layout which corresponds to release r2020-05-30 (and some previous versions).

(In the later versions, I brought back the ellipsis (…), like in EurKEY, and I moved the pilcrow (¶) to the place of the so-called "comma quotation mark" on number 8 (the "single low-9 quotation mark" is very rarely used in Germany, looks like a comma and is now on a dead key).)

Enjoy it !

**Comment by janjonckers** [comment]
Thank you,
I will certainly have a look at the latest version. Anyway thank you very much for the handy layout.

It took some effort since all the keys are double casted and double covered with resin. Some are not perfect yet, due to some flaws in the rather complicated proces of casting the typography into the keys themself. Otherwise they would rapidly wear out. At this moment it would be rather simple since I have more control concerning the technique used (which I figured out myself btw).

Anyway since I'm Belgian (like you I suppose) and I learned typewriting at school years ago, I prefer the layout of the azerty keyboard only for the keys A Z Q W and for their shift function (capital letters). Also the M-key and the ";" I would like to have their places switched . Certainly in writing long plain text it feels more natural to me. Concerning all the other keys I'm more happy with it in comparison to the rather unhandy azerty for coding. The SW variant is indeed more handy if you have a full-key keyboard with numpad.

I'm an absolute beginner in Autohotkey (studying it at this moment) and already tried to switch those positions but I do not succeed in writing a consistent code for it. Especially the ;-key gives me problems without spoiling the coding.

I will post a photo showing what I tried to achieve...

Grtz and thanks. 
![20200613_113949](https://user-images.githubusercontent.com/66851819/84565685-0ed27180-ad6b-11ea-9339-3c10e2032288.jpg)

**Comment by pieter-degroote** [comment]
In the following folder, I have put slightly modified versions which should be more 'compatible' for AZERTY keyboards :

**[https://github.com/pieter-degroote/UltimateKEYS-testing/tree/master/azerty-test](https://github.com/pieter-degroote/UltimateKEYS-testing/tree/master/azerty-test)**

In these test versions, the letters are in the AZERTY layout and the "Smart error-tolerant optimization for circumflex in French" has been 're-adjusted' for error tolerance with â/Â.

**Comment by janjonckers** [comment]
Thank you again, 

It seems to work perfect for me in SW layout, and I noticed this is the newest version.

I will keep following your good work trying to achieve the perfect keyboard...

greetings,
jan.

**Comment by pieter-degroote** [comment]
A minor change has already been made to the AZERTY variant...

**Comment by pieter-degroote** [comment]
### Important - Please note :

**When changing the Windows password, using the AZERTY variant can INTERFERE in some special cases where your keystrokes are either registered as AZERTY or as QWERTY (depending on system layer versus application layer...).**

**On the login screen, the script will NOT be loaded (normally), which can result in the WRONG input !**

**To be "better safe than sorry", you should ALWAYS make your password visible during modification, to avoid being locked out of your account !**

**Thank you for taking note of this limitation.**

**Comment by pieter-degroote** [comment]
Read more about this issue in this post :

**[github.com/pieter-degroote/UltimateKEYS/issues/3](https://github.com/pieter-degroote/UltimateKEYS/issues/3)**
