### ISSUE TITLE
PDF or image cheat sheet?

### ISSUE THREAD

**Issue by zyxir** [pieter-degroote/UltimateKEYS#5]
Hello Pieter, I'm currently actively using UltimateKEYS as my daily keyboard layout and eager to do something to make it better.

I want to make a cheat sheet for UltimateKEYS, just like that of EurKEY. You can see it here: [EurKEY cheatsheet](https://eurkey.steffen.bruentjen.eu/download/windows/1.3/eurkey-layout-complete.pdf)

I want to make this cheat sheet in PDF format so that it could be easily printed. Also there could be a JPG or PNG version so that I can use it as my desktop wallpaper.

The documentation in your website has two problems. First it's too long, and second the fonts are in a mess. Using a nicely composed PDF or image format could solve this.

So in order to make this cheat sheet, what tools can I use? Are there any recommendations? Thank you!

**Comment by pieter-degroote** [comment]
At this moment, I have updated the website (quite a lot...) to put everything there in a more structured way.

Because the whole documentation is very detailed, I think that it might be (very) difficult to put it on one or two pages.

In the past, I started creating the documentation from the MSKLC source files by using Notepad++.
To create a proper layout image, I used [KbdEdit](http://www.kbdedit.com/) (which I paid a license for).

As far as I see, I do not know which tools were exactly used to create the EurKEY cheat sheet. I might well have been a program like [GIMP](https://www.gimp.org/) (or Adobe Photoshop).

Further on, a lot of programs, like [LibreOffice](https://www.libreoffice.org/) and [IrfanView](https://www.irfanview.com/)/[XnView](https://www.xnview.com/) allow you to save as PDF...

Considering that during the past year, I was (perhaps) the only one who used UltimateKEYS, I have not put so much effort in creating some concise documentation yet.
Maybe, the keyboard layout image can converted (see attached PDF).

[UltimateKEYS - Keyboard Layout Image.pdf](https://github.com/pieter-degroote/UltimateKEYS/files/4808241/UltimateKEYS.-.Keyboard.Layout.Image.pdf)

**Comment by zyxir** [comment]
Thank you for your software recommendations!

I know how to turn a picture or webpage into a PDF, and what I really meant is something compact enough, to show both the layout (the keyboard layout diagram) and those symbols that can only be typed with a dead key.

I'll try to make such a picture of cheat sheet with **GIMP** (which I've been using for a while) and **KbdEdit** free demo version, with a monochrome Unicode font.

**Comment by pieter-degroote** [comment]
At this moment, I am working with :

[http://www.keyboard-layout-editor.com/](http://www.keyboard-layout-editor.com/)

I am going to use this tool, as it also creates keyboard layout images :

[UltimateKEYS Image](http://www.keyboard-layout-editor.com/##@@_c=#0075ff&f:4;&=~%0A%60%0A~%0A%60&_c=#cccccc;&=!%0A1%0A%C2%B9%0A%C2%A1&=/@%0A2%0A%C2%B2%0A%C2%A9&=#%0A3%0A%C2%B3%0A%C2%B1&=$%0A4%0A%C2%A5%0A%C2%A3&=%25%0A5%0A%C2%A2%0A%E2%82%AC&_c=#0075ff;&=%5E%0A6%0A%CB%87%0A%5E&=/&%0A7%0A%C2%AF%0A%CB%9A&_c=#cccccc;&=*%0A8%0A%C2%B6%0A%E2%80%9E&=(%0A9%0A%E2%80%98%0A%E2%80%9C&=)%0A0%0A%E2%80%99%0A%E2%80%9D&_c=#0075ff;&=/_%0A-%0A%CB%98%0A%C2%B8&_c=#cccccc;&=+%0A/=%0A%C3%B7%0A%C3%97&_w:2;&=Backspace;&@_w:1.5;&=Tab&=Q%0Aq%0A%C3%86%0A%C3%A6&=W%0Aw%0A%C3%85%0A%C3%A5&=E%0Ae%0A%C3%8B%0A%C3%AB&=R%0Ar%0A%C3%9D%0A%C3%BD&=T%0At%0A%C3%9E%0A%C3%BE&=Y%0Ay%0A%C5%B8%0A%C3%BF&=U%0Au%0A%C3%9C%0A%C3%BC&=I%0Ai%0A%C3%8F%0A%C3%AF&=O%0Ao%0A%C3%96%0A%C3%B6&=P%0Ap%0A%E2%80%A1%0A%E2%80%A0&=%7B%0A%5B%0A%E2%80%B9%0A%C2%AB&=%7D%0A%5D%0A%E2%80%BA%0A%C2%BB&_x:0.25&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25;&=Enter;&@_w:1.75;&=Caps%20Lock&=A%0Aa%0A%C3%84%0A%C3%A4&=S%0As%0A%C2%A7%0A%C3%9F&=D%0Ad%0A%C3%90%0A%C3%B0&=F%0Af%0A%C3%88%0A%C3%A8&=G%0Ag%0A%C3%89%0A%C3%A9&=H%0Ah%0A%C3%99%0A%C3%B9&=J%0Aj%0A%C3%9A%0A%C3%BA&=K%0Ak%0A%C5%92%0A%C5%93&=L%0Al%0A%C3%98%0A%C3%B8&=/:%0A/;%0A%C2%B7%0A%C2%B0&_c=#0075ff;&=%22%0A'%0A%C2%A8%0A%C2%B4&=%7C%0A%5C%0A%C2%A6%0A%C2%AC;&@_c=#cccccc&w:1.25;&=Shift&=%7C%0A%5C&=Z%0Az%0A%C3%80%0A%C3%A0&=X%0Ax%0A%C3%81%0A%C3%A1&=C%0Ac%0A%C3%87%0A%C3%A7&=V%0Av%0A%C3%8C%0A%C3%AC&=B%0Ab%0A%C3%8D%0A%C3%AD&=N%0An%0A%C3%91%0A%C3%B1&_c=#0075ff;&=M%0Am%0A%E2%88%9A%0A%CE%BC&_c=#cccccc;&=%3C%0A,%0A%C3%92%0A%C3%B2&=%3E%0A.%0A%C3%93%0A%C3%B3&=?%0A//%0A%E2%80%A6%0A%C2%BF&_w:2.75;&=Shift;&@_w:1.25;&=Ctrl&_w:1.25;&=Win&_w:1.25;&=Alt&_a:7&w:6.25;&=&_a:4&w:1.25;&=AltGr&_w:1.25;&=Win&_w:1.25;&=Menu&_w:1.25;&=Ctrl)

[UltimateKEYS SW Image](http://www.keyboard-layout-editor.com/##@@_c=#0075ff&f:4;&=~%0A%60%0A~%0A%60&_c=#cccccc;&=1%0A!%0A%C2%B9%0A%C2%A1&=2%0A/@%0A%C2%B2%0A%C2%A9&=3%0A#%0A%C2%B3%0A%C2%B1&=4%0A$%0A%C2%A5%0A%C2%A3&=5%0A%25%0A%C2%A2%0A%E2%82%AC&_c=#0075ff;&=6%0A%5E%0A%CB%87%0A%5E&=7%0A/&%0A%C2%AF%0A%CB%9A&_c=#cccccc;&=8%0A*%0A%C2%B6%0A%E2%80%9E&=9%0A(%0A%E2%80%98%0A%E2%80%9C&=0%0A)%0A%E2%80%99%0A%E2%80%9D&_c=#0075ff;&=/_%0A-%0A%CB%98%0A%C2%B8&_c=#cccccc;&=+%0A/=%0A%C3%B7%0A%C3%97&_w:2;&=Backspace;&@_w:1.5;&=Tab&=Q%0Aq%0A%C3%86%0A%C3%A6&=W%0Aw%0A%C3%85%0A%C3%A5&=E%0Ae%0A%C3%8B%0A%C3%AB&=R%0Ar%0A%C3%9D%0A%C3%BD&=T%0At%0A%C3%9E%0A%C3%BE&=Y%0Ay%0A%C5%B8%0A%C3%BF&=U%0Au%0A%C3%9C%0A%C3%BC&=I%0Ai%0A%C3%8F%0A%C3%AF&=O%0Ao%0A%C3%96%0A%C3%B6&=P%0Ap%0A%E2%80%A1%0A%E2%80%A0&=%7B%0A%5B%0A%E2%80%B9%0A%C2%AB&=%7D%0A%5D%0A%E2%80%BA%0A%C2%BB&_x:0.25&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25;&=Enter;&@_w:1.75;&=Caps%20Lock&=A%0Aa%0A%C3%84%0A%C3%A4&=S%0As%0A%C2%A7%0A%C3%9F&=D%0Ad%0A%C3%90%0A%C3%B0&=F%0Af%0A%C3%88%0A%C3%A8&=G%0Ag%0A%C3%89%0A%C3%A9&=H%0Ah%0A%C3%99%0A%C3%B9&=J%0Aj%0A%C3%9A%0A%C3%BA&=K%0Ak%0A%C5%92%0A%C5%93&=L%0Al%0A%C3%98%0A%C3%B8&=/:%0A/;%0A%C2%B7%0A%C2%B0&_c=#0075ff;&=%22%0A'%0A%C2%A8%0A%C2%B4&=%7C%0A%5C%0A%C2%A6%0A%C2%AC;&@_c=#cccccc&w:1.25;&=Shift&=%7C%0A%5C&=Z%0Az%0A%C3%80%0A%C3%A0&=X%0Ax%0A%C3%81%0A%C3%A1&=C%0Ac%0A%C3%87%0A%C3%A7&=V%0Av%0A%C3%8C%0A%C3%AC&=B%0Ab%0A%C3%8D%0A%C3%AD&=N%0An%0A%C3%91%0A%C3%B1&_c=#0075ff;&=M%0Am%0A%E2%88%9A%0A%CE%BC&_c=#cccccc;&=%3C%0A,%0A%C3%92%0A%C3%B2&=%3E%0A.%0A%C3%93%0A%C3%B3&=?%0A//%0A%E2%80%A6%0A%C2%BF&_w:2.25&w2:2.75;&=Shift;&@_w:1.25;&=Ctrl&_w:1.25;&=Win&_w:1.25;&=Alt&_a:7&w:6.25;&=&_a:4&w:1.25;&=AltGr&_w:1.25;&=Win&_w:1.25;&=Menu&_w:1.25;&=Ctrl)

**Comment by pieter-degroote** [comment]
Another temporal version :
[Keyboard layout image](http://www.keyboard-layout-editor.com/##@@_c=#0075ff&f:7&w:1.25&h:1.25;&=~%0A%60%0A~%0A%60&_c=#cccccc&w:1.25&h:1.25;&=!%0A1%0A%C2%B9%0A%C2%A1&_w:1.25&h:1.25;&=/@%0A2%0A%C2%B2%0A%C2%A9&_w:1.25&h:1.25;&=#%0A3%0A%C2%B3%0A%C2%B1&_w:1.25&h:1.25;&=$%0A4%0A%C2%A5%0A%C2%A3&_w:1.25&h:1.25;&=%25%0A5%0A%C2%A2%0A%E2%82%AC&_c=#0075ff&w:1.25&h:1.25;&=%5E%0A6%0A%CB%87%0A%5E&_w:1.25&h:1.25;&=/&%0A7%0A%C2%AF%0A%CB%9A&_c=#cccccc&w:1.25&h:1.25;&=*%0A8%0A%C2%B6%0A%E2%80%9E&_w:1.25&h:1.25;&=(%0A9%0A%E2%80%98%0A%E2%80%9C&_w:1.25&h:1.25;&=)%0A0%0A%E2%80%99%0A%E2%80%9D&_c=#0075ff&w:1.25&h:1.25;&=/_%0A-%0A%CB%98%0A%C2%B8&_c=#cccccc&w:1.25&h:1.25;&=+%0A/=%0A%C3%B7%0A%C3%97&_w:2.25&h:1.25;&=Backspace;&@_y:0.25&w:1.75&h:1.25;&=Tab&_w:1.25&h:1.25;&=Q%0Aq%0A%C3%86%0A%C3%A6&_w:1.25&h:1.25;&=W%0Aw%0A%C3%85%0A%C3%A5&_w:1.25&h:1.25;&=E%0Ae%0A%C3%8B%0A%C3%AB&_w:1.25&h:1.25;&=R%0Ar%0A%C3%9D%0A%C3%BD&_w:1.25&h:1.25;&=T%0At%0A%C3%9E%0A%C3%BE&_w:1.25&h:1.25;&=Y%0Ay%0A%C5%B8%0A%C3%BF&_w:1.25&h:1.25;&=U%0Au%0A%C3%9C%0A%C3%BC&_w:1.25&h:1.25;&=I%0Ai%0A%C3%8F%0A%C3%AF&_w:1.25&h:1.25;&=O%0Ao%0A%C3%96%0A%C3%B6&_w:1.25&h:1.25;&=P%0Ap%0A%E2%80%A1%0A%E2%80%A0&_w:1.25&h:1.25;&=%7B%0A%5B%0A%E2%80%B9%0A%C2%AB&_w:1.25&h:1.25;&=%7D%0A%5D%0A%E2%80%BA%0A%C2%BB&_c=#0075ff&w:1.75&h:1.25;&=%7C%0A%5C%0A%C2%A6%0A%C2%AC;&@_y:0.25&c=#cccccc&w:2.25&h:1.25;&=Caps%20Lock&_w:1.25&h:1.25;&=A%0Aa%0A%C3%84%0A%C3%A4&_w:1.25&h:1.25;&=S%0As%0A%C2%A7%0A%C3%9F&_w:1.25&h:1.25;&=D%0Ad%0A%C3%90%0A%C3%B0&_w:1.25&h:1.25;&=F%0Af%0A%C3%88%0A%C3%A8&_w:1.25&h:1.25;&=G%0Ag%0A%C3%89%0A%C3%A9&_w:1.25&h:1.25;&=H%0Ah%0A%C3%99%0A%C3%B9&_w:1.25&h:1.25;&=J%0Aj%0A%C3%9A%0A%C3%BA&_w:1.25&h:1.25;&=K%0Ak%0A%C5%92%0A%C5%93&_w:1.25&h:1.25;&=L%0Al%0A%C3%98%0A%C3%B8&_w:1.25&h:1.25;&=/:%0A/;%0A%C2%B7%0A%C2%B0&_c=#0075ff&w:1.25&h:1.25;&=%22%0A'%0A%C2%A8%0A%C2%B4&_x:0.25&c=#cccccc&w:2.25&h:1.25&x2:-0.25;&=Enter;&@_y:0.25&w:1.75&h:1.25;&=Shift&_w:1.25&h:1.25;&=%7C%0A%5C&_w:1.25&h:1.25;&=Z%0Az%0A%C3%80%0A%C3%A0&_w:1.25&h:1.25;&=X%0Ax%0A%C3%81%0A%C3%A1&_w:1.25&h:1.25;&=C%0Ac%0A%C3%87%0A%C3%A7&_w:1.25&h:1.25;&=V%0Av%0A%C3%8C%0A%C3%AC&_w:1.25&h:1.25;&=B%0Ab%0A%C3%8D%0A%C3%AD&_w:1.25&h:1.25;&=N%0An%0A%C3%91%0A%C3%B1&_c=#0075ff&w:1.25&h:1.25;&=M%0Am%0A%E2%88%9A%0A%CE%BC&_c=#cccccc&w:1.25&h:1.25;&=%3C%0A,%0A%C3%92%0A%C3%B2&_w:1.25&h:1.25;&=%3E%0A.%0A%C3%93%0A%C3%B3&_w:1.25&h:1.25;&=?%0A//%0A%E2%80%A6%0A%C2%BF&_w:3&h:1.25;&=Shift;&@_y:0.25&w:1.5&h:1.25;&=Ctrl&_w:1.5&h:1.25;&=Win&_w:1.5&h:1.25;&=Alt&_a:7&w:8&h:1.25;&=&_a:4&w:1.5&h:1.25;&=AltGr&_w:1.5&h:1.25;&=Win&_w:1.5&h:1.25;&=Menu&_w:1.5&h:1.25;&=Ctrl)

**Comment by pieter-degroote** [comment]
The [website](https://pieter-degroote.github.io/UltimateKEYS/) has now been updated with the new layout images as they are made by the open-source tool.

**Comment by zyxir** [comment]
Haha it's funny because I was just trying Keyboard-Layout-Editor the moment before I created this issue. I think the layout created by Keyboard-Layout-Editor is not as clear and pretty as the one you made with KbdEdit, and that was the reason I asked for software recommendations.

If you think Keyboard-Layout-Editor is okay then it's okay. I've decided that I am going to make a pdf cheat sheet with LaTeX, and hope you will love it.

**Comment by pieter-degroote** [comment]
Well, I think (and believe) that it should be better to use open-source tools.
I am also going to release the website and its contents (including documentation) under the GNU Free Documentation License.
In a certain way, I began testing Keyboard-Layout-Editor yesterday and I found out how I could get it in shape (finally).
