### ISSUE TITLE
Question about GPL3

### ISSUE THREAD

**Issue by zyxir** [pieter-degroote/UltimateKEYS#8]
Finally, I decided to implement my own international layout, which is **specially designed for Chinese users (it should work fine with a Chinese input method)**. I decided to call it the ZultiKEYS. But I still love your layout very much.

If I use your layout scheme, but implement it with my own AutoHotkey script where every line of code is written with my own consideration, without any copy of any code from your project, is it necessary that I license my work under GPL3 as well?

In fact, I prefer the MIT license. If I want to use the MIT license, should I design my own layout that is different from the layout scheme of UltimateKEYS?

**Comment by pieter-degroote** [comment]
Technically, the UltimateKEYS layout is derived from [EurKEY (by Steffen Brüntjen)](https://eurkey.steffen.bruentjen.eu/).
EurKEY is also GPL v3 (+ MIT for Linux). This way, UltimateKEYS is GPL v3 too. My documentation has the accompanying '[GNU Free Documentation License v1.3](https://www.gnu.org/licenses/fdl-1.3.html)'.

In case you like, you can use the MIT license.
See also this post (EurKEY for Linux is also MIT licensed) :  [https://bugs.freedesktop.org/show_bug.cgi?id=31658](https://bugs.freedesktop.org/show_bug.cgi?id=31658)

**Comment by zyxir** [comment]
Thank you for answering me!
